version: '3.8'

services:
  employee-app-serv1:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: employee
      DB_HOST: employee-db
    depends_on:
      - employee-db
  
  employee-app-serv2:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: employee
      DB_HOST: employee-db
    depends_on:
      - employee-db

  employee-app-serv3:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: employee
      DB_HOST: employee-db
    depends_on:
      - employee-db
  
  employee-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee
    volumes:
      - ./dbdata:/var/lib/mysql:rw
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - employee-app-serv1
      - employee-app-serv2
      - employee-app-serv3
    ports:
      - 8080:5000
    restart:
      always
  
  backup:
    build:
      context: .
      dockerfile: ./docker/backup_daemon/Dockerfile
    depends_on:
      - employee-db
    volumes:
      - ./dbdata:/data/:ro
      - ./backup:/backup/
    restart:
      always