name: Push and deploy

on:
  push:
    branches:
      - "master"

jobs:
  Build-and_Push:
    runs-on: ubuntu-latest 
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Stop Running Containers
      run: make down
    -
      name: Build images
      run: make build
    -
      name: Push images
      run: make push
  Fake-Deploy:
    runs-on: ubuntu-latest
    steps:
    -
      name: Challenge
      id: challenge
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://fdeployserver.up.railway.app/challenge"
        method: 'GET'
    -
      name: Get and add numbers
      id: getnumbers
      env:
        NUM1: ${{ fromJson(steps.challenge.outputs.response).num1 }}
        NUM2: ${{ fromJson(steps.challenge.outputs.response).num2 }}
        token: ${{ fromJson(steps.challenge.outputs.response).token }}
      run: |
        echo "token=$token" >> $GITHUB_OUTPUT
        echo "answer=$(($NUM1 + $NUM2))" >> $GITHUB_OUTPUT
    -
      name: Deploy
      id: deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://fdeployserver.up.railway.app/deploy"
        method: 'POST'
        data: '{"token": $${{ steps.getnumbers.outputs.token }}, "answer": $${{ steps.getnumbers.outputs.answer }}'
    -
      name: Get Result
      run: |
        echo ${{ steps.deploy.outputs.response }}
