name: Push and deploy

on:
  push:
    branches:
      - "master"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Stop Running Containers
      run: make down
    -
      name: Build images
      run: make build
    -
      name: Push images
      run: make push
